name: Köpfe schlagen Kapital
favicon: null
layout_spectrum: 0.73796
typography_spectrum: 0.7408
title: Medienökonomische Lösungen durch angewandte Forschung
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#032146'
    - '#366195'
    - '#249567'
    - '#167a63'
    - '#0b5558'
  brandStrength: 0.6875
  lightness: 0.6875
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
